export const content = [
  { type: "p", text: "If you signed a uniform or linen service agreement and never thought about it again, you're not alone. Most business owners do exactly that — and most of them pay the price for it when their contract quietly rolls into another full term." },
  { type: "h2", text: "What auto-renewal actually means" },
  { type: "p", text: "Almost every uniform service agreement includes an auto-renewal clause. The language looks something like this:" },
  { type: "quote", text: '"The term of this agreement is for twelve (12) months from the date of the first delivery and thereafter for the same time period unless cancelled by either party, in writing, at least ninety (90) days prior to any termination date."' },
  { type: "p", text: "Translation: if you don't send a certified letter 90 days before your contract ends, it automatically renews for another full 12 months. And if you sign a 60-month agreement — which many Cintas and UniFirst contracts default to — you're looking at another 5 years." },
  { type: "callout", variant: "red", title: "Why this matters", text: "The 90-day notice window is deliberately designed to be easy to miss. Most businesses don't track their contract end dates, and even those that do often forget the 90-day buffer. By the time you realize the contract rolled over, you're locked in again." },
  { type: "h2", text: "The numbers behind missing the window" },
  { type: "p", text: "Let's say you're on a 12-month agreement at $70/week with a 40% cancellation penalty. If your contract renews without your knowledge and you try to exit 6 months in:" },
  { type: "list", items: ["Cancellation penalty = 40% × $70 × 26 remaining weeks = $728", "You're also liable for minimum billing (typically 80% of contract value) for the weeks you try to reduce service", "The vendor has no obligation to let you out early — they have a signed agreement"] },
  { type: "h2", text: "How to protect yourself" },
  { type: "p", text: "There are three things you should do immediately, whether you're reviewing an existing contract or about to sign a new one." },
  { type: "h3", text: "1. Find your renewal date today" },
  { type: "p", text: "Pull out your agreement and find the first delivery date. That's when your term started. Count forward 12 months — that's your renewal date. Then count back 90 days. That's the last day you can send written cancellation notice." },
  { type: "callout", variant: "teal", title: "Do this right now", text: "Set a calendar reminder 95 days before your renewal date — giving yourself a 5-day buffer above the 90-day requirement. Mark it as 'Uniform contract decision deadline.'" },
  { type: "h3", text: "2. Negotiate the clause before signing" },
  { type: "p", text: "If you haven't signed yet, you have maximum leverage. Ask for the cancellation notice period to be reduced from 90 days to 30 days, and request that the agreement converts to month-to-month after the initial term rather than auto-renewing." },
  { type: "h3", text: "3. Send written notice the right way" },
  { type: "p", text: "If you decide not to renew, send a certified letter to the address listed in your agreement. Keep the return receipt. Reference your contract number and state explicitly that you are providing notice of non-renewal." },
  { type: "callout", variant: "amber", title: "Common mistake", text: "Telling your route driver or account rep that you want to cancel is not written notice. Only a formal written letter sent to the company's registered address counts." },
  { type: "h2", text: "The bigger picture" },
  { type: "p", text: "The auto-renewal clause is just one of many provisions in your uniform agreement designed to protect the vendor, not you. The cancellation penalty, minimum billing guarantee, price escalation language, and arbitration clause all work together to make it expensive and difficult to leave. Knowing what to ask for is half the battle." },
];