// Single-use discount codes generated by the chat assistant.
// Stored client-side in localStorage. Replace with server-side validation
// (Stripe coupons + DB tracking) when wiring up real auth + payments.

const STORAGE_KEY = "mcd_discount_codes";

export type DiscountCode = {
  code: string;
  plan: string;            // which plan id this code applies to
  discountPct: number;     // e.g. 0.10 for 10%
  createdAt: number;
  used: boolean;
  usedAt?: number;
  source: "chat-assistant" | "manual";
};

export type DiscountCodeStore = Record<string, DiscountCode>;

function read(): DiscountCodeStore {
  if (typeof window === "undefined") return {};
  try {
    return JSON.parse(window.localStorage.getItem(STORAGE_KEY) || "{}");
  } catch {
    return {};
  }
}

function write(store: DiscountCodeStore) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(store));
}

function randomSegment(len: number): string {
  // Avoid characters that look alike: 0/O, 1/I/L
  const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
  let out = "";
  for (let i = 0; i < len; i++) {
    out += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return out;
}

export function generateProAnnualDiscount(): DiscountCode {
  // Only allow ONE active discount per user. If they already have an unused
  // one, return it (so the chat assistant can't spam-generate codes).
  const store = read();
  const existing = Object.values(store).find(c => !c.used && c.plan === "pro-annual" && c.source === "chat-assistant");
  if (existing) return existing;

  const code = `MCD-PRO-${randomSegment(5)}`;
  const discount: DiscountCode = {
    code,
    plan: "pro-annual",
    discountPct: 0.10,
    createdAt: Date.now(),
    used: false,
    source: "chat-assistant",
  };
  store[code] = discount;
  write(store);
  return discount;
}

export function findDiscount(code: string): DiscountCode | undefined {
  if (!code) return undefined;
  const store = read();
  return store[code.trim().toUpperCase()];
}

export function validateDiscount(code: string, planId: string): { ok: true; discount: DiscountCode } | { ok: false; reason: string } {
  const d = findDiscount(code);
  if (!d) return { ok: false, reason: "We don't recognize that code." };
  if (d.used) return { ok: false, reason: "That code has already been redeemed." };
  if (d.plan !== planId) return { ok: false, reason: `That code is only valid for the ${d.plan} plan.` };
  return { ok: true, discount: d };
}

export function redeemDiscount(code: string) {
  const store = read();
  const d = store[code.trim().toUpperCase()];
  if (!d) return;
  d.used = true;
  d.usedAt = Date.now();
  store[code.trim().toUpperCase()] = d;
  write(store);
}
